name: Rust

on:
  push:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always
  CRATES_API_KEY: ${{ secrets.CRATES_API_KEY }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run Tests
      run: cargo test --verbose
    - name: Publish Crate
      run: |
        cargo login $CRATES_API_KEY
